Repository boostorg/website-v2, pull requests merged in 2024-11, with the labels that each got.

#1420 boostlook added, pic resized
  frontend/styles.css
  static/img/boost-toon.png
  templates/base.html
  templates/libraries/detail.html
  templates/versions/detail.html
Labels: Functionality

#1440 Fix for library version sort order
  libraries/views.py
Labels: Bug

#1430 icons links, font-awesome updated
  templates/base.html
  templates/community_temp.html
  templates/includes/_footer.html
Labels: Feature

#1449 Fix library hover text
  templates/libraries/includes/library_preferences.html
Labels: Bug

#1446 Associate the TOS label with its field
  templates/account/signup.html
Labels: Under the Hood, Maintenance
